### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by Lotarque** [soroushv/Tweet2Vec#5]
Running example sample.json.

[paulo@wormhole Tweet2Vec-master]$ THEANO_FLAGS=mode=FAST_RUN,floatX=float32 PYTHONPATH=. python model/train.py -t -i sample.json -m "new_model" -E 3
Using TensorFlow backend.
2017-06-12 18:59:47,981 - utils - INFO - Loading Data from: sample.json
2017-06-12 18:59:47,982 - utils - INFO - Loaded Data from: sample.json
Creating Training Function...
2017-06-12 19:00:29,165 - __main__ - INFO - Starting epoch 1
2017-06-12 19:00:29,166 - __main__ - INFO - Training with the Adam update function
2017-06-12 19:00:29,166 - __main__ - INFO - Training epoch 1.
2017-06-12 19:00:29,166 - __main__ - INFO - Epoch 1 results
Traceback (most recent call last):
  File "model/train.py", line 145, in <module>
    trainer.train_enc_dec(train_file=args.train_file, model_name=args.model_name, num_epochs=args.epochs,out_dir=args.out_dir)
  File "model/train.py", line 98, in train_enc_dec
    self.logger.info("Saving model parameters for epoch {0} at path {1}".format(e, ))
**IndexError: tuple index out of range**

**Comment by pl-phan** [comment]
last line : need to fill the end parenthesis.  ==> .format(e, out_path)
